### ISSUE TITLE
Corriger les url absolus en url relatifs

### ISSUE THREAD

**Issue by alienlebarge** [Schmoul622/Site-Introduction-Programmation-Frontend#1]
### Description

Il y a beaucoup d'url absolu sur dans le projet. Cela ne permet pas une portabilité du code.
Par exemple, ton projet ne tourne pas sur mon ordinateur.

### Ask

Corriger les urls absolus en relatifs

### Additional Info

exemple:
https://github.com/Schmoul622/Site-Introduction-Programmation-Frontend/blob/93db5e1b81f1ce2c4d11cf67204f9dbeed840fe9/ProjetWeb/templates/index.html#L7-L12

**Comment by Schmoul622** [comment]
Les url absolus en étaient changé en url relatif
