### ISSUE TITLE
Les attributs `alt` sont utiliser dans de mauvaise balise

### ISSUE THREAD

**Issue by alienlebarge** [Schmoul622/Site-Introduction-Programmation-Frontend#2]
### Description

Dans le html des attributs `alt` sont utilisés sur des balises qui ne le permettent pas

### Ask

Vérifier le code HTML avec le validator et corriger le code

### Additional Info

https://developer.mozilla.org/fr/docs/Web/HTML/Attributs

**Comment by Schmoul622** [comment]
Une accessibilité des liens à été ajouté on ajoutant une classe visually-hidden
