### ISSUE TITLE
Trouver un moyen de vérifier la saisie du formulaire sans js

### ISSUE THREAD

**Issue by alienlebarge** [Schmoul622/Site-Introduction-Programmation-Frontend#3]
### Description

Les champs du formulaire sont vérifés via JS. C'est bien.
Mais comment cela se passe si qqun a le javascript désactivé dans son browser ?

### Ask

Trouver un moyen de vérifier la saisie sans JS (est-ce que c'est bien une adresse mail ?, etc.).

### Additional Info

...

**Comment by Schmoul622** [comment]
La vérification du formulaire se fait désormais directement dans le code html
